# Preprocessing static variables

In [1]:
import pandas as pd
import datetime
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
mimic_static = pd.read_csv("./data/mimic_dems.csv")
mimic_static.head()

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,hospital_expire_flag,icd9_code,short_title,subject_id,gender,dob,dod,los
0,174105,2194-06-13 18:39:00,2194-06-18 16:50:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,JEWISH,MARRIED,WHITE,0,53100,Ac stomach ulcer w hem,112,M,1894-06-13 00:00:00,2196-09-29 00:00:00,0.8402
1,174105,2194-06-13 18:39:00,2194-06-18 16:50:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,JEWISH,MARRIED,WHITE,0,41071,"Subendo infarct, initial",112,M,1894-06-13 00:00:00,2196-09-29 00:00:00,0.8402
2,174105,2194-06-13 18:39:00,2194-06-18 16:50:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,JEWISH,MARRIED,WHITE,0,2859,Anemia NOS,112,M,1894-06-13 00:00:00,2196-09-29 00:00:00,0.8402
3,174105,2194-06-13 18:39:00,2194-06-18 16:50:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,JEWISH,MARRIED,WHITE,0,41401,Crnry athrscl natve vssl,112,M,1894-06-13 00:00:00,2196-09-29 00:00:00,0.8402
4,174105,2194-06-13 18:39:00,2194-06-18 16:50:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicare,NaN,JEWISH,MARRIED,WHITE,0,725,Polymyalgia rheumatica,112,M,1894-06-13 00:00:00,2196-09-29 00:00:00,0.8402

In [5]:
mimic_lab_CV = pd.read_csv("./data/mimic_lab_CV_reg_pre.csv")
mimic_lab_MV = pd.read_csv("./data/mimic_lab_MV_reg_pre.csv")
mimic_chart_CV = pd.read_csv("./data/mimic_chart_CV_reg_pre.csv")
mimic_chart_MV = pd.read_csv("./data/mimic_chart_MV_reg_pre.csv")

/Users/shutingcui/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (9,11,14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/Users/shutingcui/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (9,11) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:
mimic_static_hadm_id = mimic_static["hadm_id"].unique()
mimic_CV_hadm_id = mimic_chart_CV["hadm_id"].unique()
mimic_MV_hadm_id = mimic_chart_MV["hadm_id"].unique()
mimic_static_CV_hadm_id = set(mimic_static_hadm_id).intersection(mimic_CV_hadm_id)
mimic_static_MV_hadm_id = set(mimic_static_hadm_id).intersection(mimic_MV_hadm_id)

In [7]:
print(len(mimic_static_hadm_id))
print(len(mimic_CV_hadm_id))
print(len(mimic_static_CV_hadm_id))
print(len(mimic_MV_hadm_id))
print(len(mimic_static_MV_hadm_id))

58976
26106
26106
21125
21125

## a) divide mimic_static into 2 parts: mimic_static_CV and mimic_static_MV based on above "mimic_static_CV_hadm_id" and "mimic_static_MV_hadm_id"

In [8]:
mimic_static_CV = mimic_static[mimic_static["hadm_id"].isin(mimic_static_CV_hadm_id)]
mimic_static_MV = mimic_static[mimic_static["hadm_id"].isin(mimic_static_MV_hadm_id)]
mimic_static_CV.reset_index(drop=True, inplace=True)
mimic_static_MV.reset_index(drop=True, inplace=True)
print(mimic_static.shape)
print(mimic_static_CV.shape)
print(mimic_static_MV.shape)

(714344, 20)
(285694, 20)
(343299, 20)

## b) transfer the icd_9 codes into 1-19 categorical variable

In [9]:
def ICD9_codes_trans(org_icd9):
    if pd.isna(org_icd9):
        return np.nan
    else:
        first_3_num = org_icd9[0:3]
        transformed_icd9 = 0
        if first_3_num[0] == 'V':
            transformed_icd9 = 19
        elif first_3_num[0] == 'E':
            transformed_icd9 = 20
        else:
            code_range = float(first_3_num)
            if code_range >= 1 and code_range <= 139:
                transformed_icd9 = 1
            if code_range >= 140 and code_range <= 239:
                transformed_icd9 = 2
            if code_range >= 240 and code_range <= 279:
                transformed_icd9 = 3
            if code_range >= 280 and code_range <= 289:
                transformed_icd9 = 4
            if code_range >= 290 and code_range <= 319:
                transformed_icd9 = 5
            if code_range >= 320 and code_range <= 389:
                transformed_icd9 = 6
            if code_range >= 390 and code_range <= 459:
                transformed_icd9 = 7
            if code_range >= 460 and code_range <= 519:
                transformed_icd9 = 8
            if code_range >= 520 and code_range <= 579:
                transformed_icd9 = 9
            if code_range >= 580 and code_range <= 629:
                transformed_icd9 = 10
            if code_range >= 630 and code_range <= 679:
                transformed_icd9 = 11
            if code_range >= 680 and code_range <= 709:
                transformed_icd9 = 12
            if code_range >= 710 and code_range <= 739:
                transformed_icd9 = 13
            if code_range >= 740 and code_range <= 759:
                transformed_icd9 = 14
            if code_range >= 780 and code_range <= 789:
                transformed_icd9 = 15
            if code_range >= 790 and code_range <= 796:
                transformed_icd9 = 16
            if code_range >= 797 and code_range <= 799:
                transformed_icd9 = 17
            if code_range >= 800 and code_range <= 999:
                transformed_icd9 = 18
            
    return int(transformed_icd9)

* transfer on "mimic_static_CV "

In [10]:
mimic_static_CV.head()

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,hospital_expire_flag,icd9_code,short_title,subject_id,gender,dob,dod,los
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,19889,Secondary malig neo NEC,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174
1,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,1972,Second malig neo pleura,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174
2,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,V103,Hx of breast malignancy,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174
3,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,0,03811,Meth susc Staph aur sept,64,F,2116-06-27 00:00:00,NaN,2.3250
4,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,0,99591,Sepsis,64,F,2116-06-27 00:00:00,NaN,2.3250

In [11]:
mimic_static_CV[["transformed_icd9"]] = mimic_static_CV[["icd9_code"]].apply((lambda x: ICD9_codes_trans(x["icd9_code"])), axis=1)
mimic_static_CV[["transformed_icd9"]] = mimic_static_CV[["transformed_icd9"]].fillna(-1)
mimic_static_CV[["transformed_icd9"]] = mimic_static_CV[["transformed_icd9"]].astype(int)

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(mimic_static_CV.head())

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,hospital_expire_flag,icd9_code,short_title,subject_id,gender,dob,dod,los,transformed_icd9
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,19889,Secondary malig neo NEC,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174,2
1,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,1972,Second malig neo pleura,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174,2
2,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,V103,Hx of breast malignancy,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174,19
3,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,0,03811,Meth susc Staph aur sept,64,F,2116-06-27 00:00:00,NaN,2.3250,1
4,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,0,99591,Sepsis,64,F,2116-06-27 00:00:00,NaN,2.3250,18

* transfer on "mimic_static_MV "

In [12]:
mimic_static_MV[["transformed_icd9"]] = mimic_static_MV[["icd9_code"]].apply((lambda x: ICD9_codes_trans(x["icd9_code"])), axis=1)
mimic_static_MV[["transformed_icd9"]] = mimic_static_MV[["transformed_icd9"]].fillna(-1)
mimic_static_MV[["transformed_icd9"]] = mimic_static_MV[["transformed_icd9"]].astype(int)

with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(mimic_static_MV.head())

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,hospital_expire_flag,icd9_code,short_title,subject_id,gender,dob,dod,los,transformed_icd9
0,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,55321,Incisional hernia,36,M,2061-08-17 00:00:00,NaN,4.3483,9
1,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,41511,Iatrogen pulm emb/infarc,36,M,2061-08-17 00:00:00,NaN,4.3483,7
2,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,5185,NaN,36,M,2061-08-17 00:00:00,NaN,4.3483,8
3,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,486,"Pneumonia, organism NOS",36,M,2061-08-17 00:00:00,NaN,4.3483,8
4,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,99739,Respiratory comp NEC,36,M,2061-08-17 00:00:00,NaN,4.3483,18

## e) divide column "transformed_icd9" into 20 catogoricals: icd9_1 - icd9_20**

* transfer on mimic_static_CV

In [13]:
icd9_categories_CV = pd.get_dummies(mimic_static_CV.transformed_icd9)

In [14]:
new_columns = []
for i in range(1,21):
    new_columns.append("icd9_" + str(i))
icd9_categories_CV.columns = new_columns
mimic_static_CV = pd.concat([mimic_static_CV, icd9_categories_CV], axis=1)
mimic_static_CV.drop(['transformed_icd9', "icd9_code"], axis=1, inplace=True)
with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(mimic_static_CV.head())

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,hospital_expire_flag,short_title,subject_id,gender,dob,dod,los,icd9_1,icd9_2,icd9_3,icd9_4,icd9_5,icd9_6,icd9_7,icd9_8,icd9_9,icd9_10,icd9_11,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,Secondary malig neo NEC,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,Second malig neo pleura,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,0,Hx of breast malignancy,127,F,2135-02-01 00:00:00,2184-02-22 00:00:00,3.9174,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,0,Meth susc Staph aur sept,64,F,2116-06-27 00:00:00,NaN,2.3250,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,0,Sepsis,64,F,2116-06-27 00:00:00,NaN,2.3250,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

* transfer on mimic_static_MV

## For mimic_static_MV, there is a row with "icd9_code" == 76076, the first three number "760" is not included in the cases function "ICD9_codes_trans" tackles. Just delete this row

In [15]:
mimic_static_MV[mimic_static_MV["icd9_code"] == "76076"]

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,...,ethnicity,hospital_expire_flag,icd9_code,short_title,subject_id,gender,dob,dod,los,transformed_icd9
134735,140225,2163-11-05 02:37:00,2163-11-17 13:51:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME HEALTH CARE,Private,ENGL,JEWISH,...,WHITE,0,76076,Maternal DES af NB/fetus,66780,F,2108-02-05 00:00:00,NaN,2.9018,0

In [16]:
mimic_static_MV.drop(mimic_static_MV[mimic_static_MV["icd9_code"] == "76076"].index, axis=0, inplace=True)

In [17]:
mimic_static_MV.reset_index(drop=True, inplace=True)

In [18]:
# To check whether successfully delete the row with "icd9_code" == 76076
mimic_static_MV[mimic_static_MV["icd9_code"] == "76076"]

Empty DataFrame
Columns: [hadm_id, admittime, dischtime, deathtime, admission_type, admission_location, discharge_location, insurance, language, religion, marital_status, ethnicity, hospital_expire_flag, icd9_code, short_title, subject_id, gender, dob, dod, los, transformed_icd9]
Index: []

[0 rows x 21 columns]

In [19]:
mimic_static_MV.head()

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,...,ethnicity,hospital_expire_flag,icd9_code,short_title,subject_id,gender,dob,dod,los,transformed_icd9
0,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,...,WHITE,0,55321,Incisional hernia,36,M,2061-08-17 00:00:00,NaN,4.3483,9
1,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,...,WHITE,0,41511,Iatrogen pulm emb/infarc,36,M,2061-08-17 00:00:00,NaN,4.3483,7
2,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,...,WHITE,0,5185,NaN,36,M,2061-08-17 00:00:00,NaN,4.3483,8
3,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,...,WHITE,0,486,"Pneumonia, organism NOS",36,M,2061-08-17 00:00:00,NaN,4.3483,8
4,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,...,WHITE,0,99739,Respiratory comp NEC,36,M,2061-08-17 00:00:00,NaN,4.3483,18

In [20]:
icd9_categories_MV = pd.get_dummies(mimic_static_MV.transformed_icd9)

In [21]:
icd9_categories_MV.columns = new_columns
mimic_static_MV = pd.concat([mimic_static_MV, icd9_categories_MV], axis=1)
mimic_static_MV.drop(['transformed_icd9', "icd9_code"], axis=1, inplace=True)
with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(mimic_static_MV.head())

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,hospital_expire_flag,short_title,subject_id,gender,dob,dod,los,icd9_1,icd9_2,icd9_3,icd9_4,icd9_5,icd9_6,icd9_7,icd9_8,icd9_9,icd9_10,icd9_11,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20
0,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,Incisional hernia,36,M,2061-08-17 00:00:00,NaN,4.3483,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,Iatrogen pulm emb/infarc,36,M,2061-08-17 00:00:00,NaN,4.3483,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,NaN,36,M,2061-08-17 00:00:00,NaN,4.3483,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
3,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,"Pneumonia, organism NOS",36,M,2061-08-17 00:00:00,NaN,4.3483,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,0,Respiratory comp NEC,36,M,2061-08-17 00:00:00,NaN,4.3483,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

## g) combine rows with same hadm_id into one row by moving all the 1 values in columns "icd9_xx" into the first row of the same-adm_id-group

* transfer on mimic_static_CV

## f) **drop column "hospital_expire_flag" & "short title"because they're redundant with "discharge_location"**
## drop columns "subject_id", "los" which is usless for generating the static variables and will cause redundant rows for the same hadm_id (because of the difference in columns "subject_id" and "los"(length of stay))

In [22]:
all_hadm_id_unique_CV = list(mimic_static_CV["hadm_id"].unique())
new_mimic_CV_gb_adm_id = mimic_static_CV.groupby("hadm_id")
final_formatted_static_CV = 0
for i, item in enumerate(all_hadm_id_unique_CV):
#     if (i+1) % 10000 == 0:
#         print("current transform patient: ", i+1)
#         print("current final_formatted_static_var's shape: ", final_formatted_static_var.shape)
    cur_patient = new_mimic_CV_gb_adm_id.get_group(item)
    cur_patient_icd9_cols = cur_patient[new_columns]
    for j in range(20):
        if (cur_patient_icd9_cols.iloc[:, j]==0).all():
            continue
        else:
            cur_patient_icd9_cols.iloc[0, j] = 1
# dropping cols "hospital_expire_flag", "short_title", "subject_id", and "los" is for successfully dropping duplicates later
    cur_patient.drop(columns = new_columns+["hospital_expire_flag", "short_title", "subject_id", "los"], axis=1, inplace=True)
    cur_patient.drop_duplicates(inplace=True)
    cur_combined_icd9_codes = cur_patient_icd9_cols.iloc[[0]]
    cur_patient_formatted_static_CV = pd.concat([cur_patient, cur_combined_icd9_codes], axis=1)
    if i == 0:
        final_formatted_static_CV = cur_patient_formatted_static_CV
    else:
        final_formatted_static_CV = pd.concat([final_formatted_static_CV, cur_patient_formatted_static_CV], axis=0)

In [23]:
final_formatted_static_CV.reset_index(drop=True, inplace=True)

In [26]:
final_formatted_static_CV.shape

(26106, 35)

In [25]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(final_formatted_static_CV.head())

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,gender,dob,dod,icd9_1,icd9_2,icd9_3,icd9_4,icd9_5,icd9_6,icd9_7,icd9_8,icd9_9,icd9_10,icd9_11,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,SINGLE,WHITE,F,2135-02-01 00:00:00,2184-02-22 00:00:00,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,F,2116-06-27 00:00:00,NaN,1,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,0,1,0,0
2,142768,2164-11-18 07:00:00,2164-11-20 14:30:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,CATHOLIC,MARRIED,UNKNOWN/NOT SPECIFIED,M,2119-05-12 00:00:00,NaN,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,158569,2142-04-01 12:34:00,2142-04-08 14:46:00,NaN,URGENT,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,NaN,UNOBTAINABLE,MARRIED,UNKNOWN/NOT SPECIFIED,F,2076-09-15 00:00:00,2142-11-20 00:00:00,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0
4,170324,2156-03-31 16:11:00,2156-04-29 15:05:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Government,ENGL,CATHOLIC,MARRIED,WHITE,M,2117-10-02 00:00:00,NaN,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0

* transfer on mimic_static_MV

In [27]:
all_hadm_id_unique_MV = list(mimic_static_MV["hadm_id"].unique())
new_mimic_MV_gb_adm_id = mimic_static_MV.groupby("hadm_id")
final_formatted_static_MV = 0
for i, item in enumerate(all_hadm_id_unique_MV):
#     if (i+1) % 10000 == 0:
#         print("current transform patient: ", i+1)
#         print("current final_formatted_static_var's shape: ", final_formatted_static_var.shape)
    cur_patient = new_mimic_MV_gb_adm_id.get_group(item)
    cur_patient_icd9_cols = cur_patient[new_columns]
    for j in range(20):
        if (cur_patient_icd9_cols.iloc[:, j]==0).all():
            continue
        else:
            cur_patient_icd9_cols.iloc[0, j] = 1
    cur_patient.drop(columns = new_columns+["hospital_expire_flag", "short_title", "subject_id", "los"], axis=1, inplace=True)
    cur_patient.drop_duplicates(inplace=True)
    cur_combined_icd9_codes = cur_patient_icd9_cols.iloc[[0]]
    cur_patient_formatted_static_MV = pd.concat([cur_patient, cur_combined_icd9_codes], axis=1)
    if i == 0:
        final_formatted_static_MV = cur_patient_formatted_static_MV
    else:
        final_formatted_static_MV = pd.concat([final_formatted_static_MV, cur_patient_formatted_static_MV], axis=0)

In [28]:
final_formatted_static_MV.reset_index(drop=True, inplace=True)

In [29]:
final_formatted_static_MV.shape

(21125, 35)

In [30]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(final_formatted_static_MV.head())

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,marital_status,ethnicity,gender,dob,dod,icd9_1,icd9_2,icd9_3,icd9_4,icd9_5,icd9_6,icd9_7,icd9_8,icd9_9,icd9_10,icd9_11,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20
0,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,MARRIED,WHITE,M,2061-08-17 00:00:00,NaN,0,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,1,0
1,126055,2141-10-13 23:10:00,2141-11-03 18:45:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,F,2117-08-07 00:00:00,2142-08-30 00:00:00,0,0,1,1,0,1,1,1,1,1,0,0,1,0,1,1,0,0,1,0
2,136572,2142-06-18 03:11:00,2142-06-20 16:34:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,F,2117-08-07 00:00:00,2142-08-30 00:00:00,0,0,1,1,1,1,1,0,1,1,0,0,1,0,1,0,0,0,1,0
3,137510,2142-04-20 13:39:00,2142-04-22 15:30:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,F,2117-08-07 00:00:00,2142-08-30 00:00:00,0,0,1,1,0,1,1,0,0,1,0,0,1,0,1,0,0,0,1,0
4,158943,2142-03-21 09:25:00,2142-03-23 18:11:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicaid,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,F,2117-08-07 00:00:00,2142-08-30 00:00:00,1,0,1,1,0,1,1,0,0,1,0,0,1,0,1,1,0,1,1,1

In [31]:
len(final_formatted_static_CV["hadm_id"].unique())

26106

In [32]:
len(final_formatted_static_MV["hadm_id"].unique())

21125

## c) transfer the variable "dob" into the age computed from the day of birth to the admission time using "admittime" in mimic_static

* Transfer on static_CV

In [37]:
final_formatted_static_CV[["adm_year"]] = final_formatted_static_CV[["admittime"]].apply((lambda x: datetime.datetime.strptime(x["admittime"], "%Y-%m-%d %H:%M:%S").year), axis=1)
final_formatted_static_CV[["dob_year"]] = final_formatted_static_CV[["dob"]].apply((lambda x: datetime.datetime.strptime(x["dob"], "%Y-%m-%d %H:%M:%S").year), axis=1)
final_formatted_static_CV[["age"]] = final_formatted_static_CV["adm_year"] - final_formatted_static_CV["dob_year"]
final_formatted_static_CV.head()

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,...,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20,adm_year,dob_year,age
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,...,0,0,0,0,0,1,0,2183,2135,48
1,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,...,0,1,0,0,1,0,0,2143,2116,27
2,142768,2164-11-18 07:00:00,2164-11-20 14:30:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,CATHOLIC,...,0,0,0,0,0,0,0,2164,2119,45
3,158569,2142-04-01 12:34:00,2142-04-08 14:46:00,NaN,URGENT,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,NaN,UNOBTAINABLE,...,0,0,0,0,0,0,0,2142,2076,66
4,170324,2156-03-31 16:11:00,2156-04-29 15:05:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Government,ENGL,CATHOLIC,...,0,0,0,0,1,1,0,2156,2117,39

In [38]:
final_formatted_static_CV.drop(columns=["adm_year", "dob_year"], inplace=True)
final_formatted_static_CV.head()

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,...,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20,age
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,EMERGENCY,CLINIC REFERRAL/PREMATURE,HOME,Private,NaN,CATHOLIC,...,0,0,0,0,0,0,0,1,0,48
1,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,Medicaid,ENGL,OTHER,...,0,1,0,1,0,0,1,0,0,27
2,142768,2164-11-18 07:00:00,2164-11-20 14:30:00,NaN,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,CATHOLIC,...,0,0,0,0,0,0,0,0,0,45
3,158569,2142-04-01 12:34:00,2142-04-08 14:46:00,NaN,URGENT,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,NaN,UNOBTAINABLE,...,1,0,0,0,0,0,0,0,0,66
4,170324,2156-03-31 16:11:00,2156-04-29 15:05:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Government,ENGL,CATHOLIC,...,0,0,0,0,0,0,1,1,0,39

* Tranfer on static_MV

In [39]:
final_formatted_static_MV[["adm_year"]] = final_formatted_static_MV[["admittime"]].apply((lambda x: datetime.datetime.strptime(x["admittime"], "%Y-%m-%d %H:%M:%S").year), axis=1)
final_formatted_static_MV[["dob_year"]] = final_formatted_static_MV[["dob"]].apply((lambda x: datetime.datetime.strptime(x["dob"], "%Y-%m-%d %H:%M:%S").year), axis=1)
final_formatted_static_MV[["age"]] = final_formatted_static_MV["adm_year"] - final_formatted_static_MV["dob_year"]
final_formatted_static_MV.drop(columns=["adm_year", "dob_year"], inplace=True)
final_formatted_static_MV.head()

,hadm_id,admittime,dischtime,deathtime,admission_type,admission_location,discharge_location,insurance,language,religion,...,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20,age
0,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,ELECTIVE,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,Medicare,ENGL,NOT SPECIFIED,...,0,0,0,0,0,0,1,1,0,73
1,126055,2141-10-13 23:10:00,2141-11-03 18:45:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicaid,ENGL,NOT SPECIFIED,...,0,1,0,1,1,0,0,1,0,24
2,136572,2142-06-18 03:11:00,2142-06-20 16:34:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicaid,ENGL,NOT SPECIFIED,...,0,1,0,1,0,0,0,1,0,25
3,137510,2142-04-20 13:39:00,2142-04-22 15:30:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,Medicaid,ENGL,NOT SPECIFIED,...,0,1,0,1,0,0,0,1,0,25
4,158943,2142-03-21 09:25:00,2142-03-23 18:11:00,NaN,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Medicaid,ENGL,NOT SPECIFIED,...,0,1,0,1,1,0,1,1,1,25

## d) One-hot encoding other categorical variables

* Transfer on mimic_static_CV

In [40]:
final_formatted_static_CV.columns

Index(['hadm_id', 'admittime', 'dischtime', 'deathtime', 'admission_type',
       'admission_location', 'discharge_location', 'insurance', 'language',
       'religion', 'marital_status', 'ethnicity', 'gender', 'dob', 'dod',
       'icd9_1', 'icd9_2', 'icd9_3', 'icd9_4', 'icd9_5', 'icd9_6', 'icd9_7',
       'icd9_8', 'icd9_9', 'icd9_10', 'icd9_11', 'icd9_12', 'icd9_13',
       'icd9_14', 'icd9_15', 'icd9_16', 'icd9_17', 'icd9_18', 'icd9_19',
       'icd9_20', 'age'],
      dtype='object')

In [42]:
# one-hot encoding "insurance"
insurance_dummy = pd.get_dummies(final_formatted_static_CV.insurance)
final_formatted_static_CV = pd.concat([final_formatted_static_CV,insurance_dummy],axis=1) 

# one-hot encoding "admission_type"
adm_type_dummy = pd.get_dummies(final_formatted_static_CV.admission_type)
final_formatted_static_CV = pd.concat([final_formatted_static_CV, adm_type_dummy], axis=1)

# one-hot encoding "gender"
gender_dummy = pd.get_dummies(final_formatted_static_CV.gender)
final_formatted_static_CV = pd.concat([final_formatted_static_CV, gender_dummy], axis=1)

# drop the original columns where the dummy columns generated
final_formatted_static_CV.drop(['insurance', 'admission_type', 'gender'], axis=1, inplace=True)
# new_mimic_static_formatted is the final form of each admission's static variable
final_formatted_static_CV.head()

,hadm_id,admittime,dischtime,deathtime,admission_location,discharge_location,language,religion,marital_status,ethnicity,...,Government,Medicaid,Medicare,Private,Self Pay,ELECTIVE,EMERGENCY,URGENT,F,M
0,141647,2183-08-20 17:25:00,2183-08-24 15:28:00,NaN,CLINIC REFERRAL/PREMATURE,HOME,NaN,CATHOLIC,SINGLE,WHITE,...,0,0,0,1,0,0,1,0,1,0
1,172056,2143-03-03 09:25:00,2143-03-18 13:01:00,NaN,EMERGENCY ROOM ADMIT,REHAB/DISTINCT PART HOSP,ENGL,OTHER,SINGLE,BLACK/AFRICAN AMERICAN,...,0,1,0,0,0,0,1,0,1,0
2,142768,2164-11-18 07:00:00,2164-11-20 14:30:00,NaN,TRANSFER FROM HOSP/EXTRAM,HOME,NaN,CATHOLIC,MARRIED,UNKNOWN/NOT SPECIFIED,...,0,0,0,1,0,0,1,0,0,1
3,158569,2142-04-01 12:34:00,2142-04-08 14:46:00,NaN,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,NaN,UNOBTAINABLE,MARRIED,UNKNOWN/NOT SPECIFIED,...,0,0,1,0,0,0,0,1,1,0
4,170324,2156-03-31 16:11:00,2156-04-29 15:05:00,NaN,EMERGENCY ROOM ADMIT,HOME,ENGL,CATHOLIC,MARRIED,WHITE,...,1,0,0,0,0,0,1,0,0,1

* Transfer on mimic_static_MV

In [41]:
final_formatted_static_MV.columns

Index(['hadm_id', 'admittime', 'dischtime', 'deathtime', 'admission_type',
       'admission_location', 'discharge_location', 'insurance', 'language',
       'religion', 'marital_status', 'ethnicity', 'gender', 'dob', 'dod',
       'icd9_1', 'icd9_2', 'icd9_3', 'icd9_4', 'icd9_5', 'icd9_6', 'icd9_7',
       'icd9_8', 'icd9_9', 'icd9_10', 'icd9_11', 'icd9_12', 'icd9_13',
       'icd9_14', 'icd9_15', 'icd9_16', 'icd9_17', 'icd9_18', 'icd9_19',
       'icd9_20', 'age'],
      dtype='object')

In [43]:
# one-hot encoding "insurance"
insurance_dummy = pd.get_dummies(final_formatted_static_MV.insurance)
final_formatted_static_MV = pd.concat([final_formatted_static_MV,insurance_dummy],axis=1) 

# one-hot encoding "admission_type"
adm_type_dummy = pd.get_dummies(final_formatted_static_MV.admission_type)
final_formatted_static_MV = pd.concat([final_formatted_static_MV, adm_type_dummy], axis=1)

# one-hot encoding "gender"
gender_dummy = pd.get_dummies(final_formatted_static_MV.gender)
final_formatted_static_MV = pd.concat([final_formatted_static_MV, gender_dummy], axis=1)

# drop the original columns where the dummy columns generated
final_formatted_static_MV.drop(['insurance', 'admission_type', 'gender'], axis=1, inplace=True)
# new_mimic_static_formatted is the final form of each admission's static variable
with pd.option_context('display.max_rows', None, 'display.max_columns', None): 
    display(final_formatted_static_MV.head())

,hadm_id,admittime,dischtime,deathtime,admission_location,discharge_location,language,religion,marital_status,ethnicity,dob,dod,icd9_1,icd9_2,icd9_3,icd9_4,icd9_5,icd9_6,icd9_7,icd9_8,icd9_9,icd9_10,icd9_11,icd9_12,icd9_13,icd9_14,icd9_15,icd9_16,icd9_17,icd9_18,icd9_19,icd9_20,age,Government,Medicaid,Medicare,Private,Self Pay,ELECTIVE,EMERGENCY,URGENT,F,M
0,165660,2134-05-10 11:30:00,2134-05-20 13:16:00,NaN,PHYS REFERRAL/NORMAL DELI,LONG TERM CARE HOSPITAL,ENGL,NOT SPECIFIED,MARRIED,WHITE,2061-08-17 00:00:00,NaN,0,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0,1,1,0,73,0,0,1,0,0,1,0,0,0,1
1,126055,2141-10-13 23:10:00,2141-11-03 18:45:00,NaN,EMERGENCY ROOM ADMIT,HOME,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2117-08-07 00:00:00,2142-08-30 00:00:00,0,0,1,1,0,1,1,1,1,1,0,0,1,0,1,1,0,0,1,0,24,0,1,0,0,0,0,1,0,1,0
2,136572,2142-06-18 03:11:00,2142-06-20 16:34:00,NaN,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2117-08-07 00:00:00,2142-08-30 00:00:00,0,0,1,1,1,1,1,0,1,1,0,0,1,0,1,0,0,0,1,0,25,0,1,0,0,0,0,1,0,1,0
3,137510,2142-04-20 13:39:00,2142-04-22 15:30:00,NaN,EMERGENCY ROOM ADMIT,HOME HEALTH CARE,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2117-08-07 00:00:00,2142-08-30 00:00:00,0,0,1,1,0,1,1,0,0,1,0,0,1,0,1,0,0,0,1,0,25,0,1,0,0,0,0,1,0,1,0
4,158943,2142-03-21 09:25:00,2142-03-23 18:11:00,NaN,EMERGENCY ROOM ADMIT,HOME,ENGL,NOT SPECIFIED,SINGLE,BLACK/AFRICAN AMERICAN,2117-08-07 00:00:00,2142-08-30 00:00:00,1,0,1,1,0,1,1,0,0,1,0,0,1,0,1,1,0,1,1,1,25,0,1,0,0,0,0,1,0,1,0

## Totally unique num of adm_id: 26106(CV) & 21125(MV), combine all the dummy variables whose value_counts are less than 10% of 26106(CV)/21125(MV): 2610(CV)/2112(MV)

## h) **one-hot encoding categorical variable: "admission_location"**

## i) **one-hot encoding "discharge_location" categorical static variable**

## j) one-hot encoding categorical variable: "language"

## k) one-hot encoding categorical variable "religion"

## l) one-hot encoding categorical variable "marital_status"

## m) one-hot encoding categorical variable "ethnicity"